In [31]:
##Sort, Search & Counting Functions.

In [32]:
import numpy as np

In [33]:
arr = np.array([4,2,8,5,3,9,12,56])

In [34]:
arr

array([ 4,  2,  8,  5,  3,  9, 12, 56])

In [35]:
np.sort(arr)

array([ 2,  3,  4,  5,  8,  9, 12, 56])

In [36]:
np.searchsorted(arr,6)

5

In [37]:
arr1 = np.array([0,324,645,65,6,6,0,0,0,234])

In [38]:
np.count_nonzero(arr1)

6

In [39]:
np.where(arr1>0)

(array([1, 2, 3, 4, 5, 9], dtype=int64),)

In [40]:
np.extract(arr1>2,arr1)

array([324, 645,  65,   6,   6, 234])

In [41]:
#Numpy - Byte Swapping.

In [42]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [43]:
arr.byteswap(True)

array([ 67108864,  33554432, 134217728,  83886080,  50331648, 150994944,
       201326592, 939524096])

In [44]:
arr

array([ 67108864,  33554432, 134217728,  83886080,  50331648, 150994944,
       201326592, 939524096])

In [45]:
#Numpy - Copies &Views.

In [46]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [47]:
a = np.copy(arr1)

In [48]:
b = arr1.view()

In [49]:
b

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [50]:
a

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [51]:
b = arr1

In [52]:
b

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [53]:
b[0]

0

In [54]:
b[1]

324

In [55]:
b[0] = 234

In [56]:
b

array([234, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [57]:
a

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [58]:
arr1

array([234, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [59]:
#Numpy - Matrix Library.

In [60]:
import numpy.matlib as nm

In [61]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [62]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [63]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [64]:
#Numpy - Linear Algebra

In [65]:
arr1 = np.random.randint([[2,3] , [4,5]])

In [66]:
arr2 = np.random.randint([[5,3] , [2,5]])

In [67]:
arr1

array([[1, 1],
       [3, 0]])

In [68]:
arr2

array([[3, 0],
       [0, 2]])

In [69]:
np.dot(arr1,arr2)

array([[3, 2],
       [9, 0]])

In [70]:
arr1@arr2

array([[3, 2],
       [9, 0]])