In [1]:
import numpy as np

In [3]:
list(range(5))

[0, 1, 2, 3, 4]

In [4]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
list(range(0.4,10.4))

TypeError: 'float' object cannot be interpreted as an integer

In [12]:
arr = np.arange(0.4,10.4,0.2)

In [14]:
arr

array([ 0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,
        2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,
        4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,
        7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,
        9.2,  9.4,  9.6,  9.8, 10. , 10.2])

In [16]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [18]:
np.logspace(1,5,num=10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [19]:
np.logspace(1,5,num=10,base = 2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [20]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [21]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [23]:
np.zeros((2,3,4,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [24]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [25]:
arr = np.ones((3,4))

In [26]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
arr + 5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [28]:
arr*4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [29]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
np.empty((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
arr1 = np.eye(4)

In [34]:
arr1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [35]:
import pandas as pd

In [36]:
pd.DataFrame(arr1)

0    1    2    3
0  1.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0
2  0.0  0.0  1.0  0.0
3  0.0  0.0  0.0  1.0

In [37]:
np.random.rand(2,3)

array([[0.83882034, 0.83707554, 0.22073385],
       [0.88419147, 0.06722937, 0.57156295]])

In [38]:
np.random.randn(2,3)

array([[-0.43328642,  1.78913275,  0.02930991],
       [ 1.45471296,  0.64131611, -0.91989475]])

In [40]:
arr2 = np.random.randint(1,4,(3,4))

In [41]:
arr2

array([[2, 1, 3, 2],
       [3, 2, 1, 3],
       [1, 3, 3, 3]])

In [43]:
arr2.size

12

In [45]:
arr2.shape

(3, 4)

In [47]:
arr2.reshape((4,3))

array([[2, 1, 3],
       [2, 3, 2],
       [1, 3, 1],
       [3, 3, 3]])

In [48]:
arr2.size

12

In [49]:
arr2.shape

(3, 4)

In [50]:
arr2.reshape(4,-1)

array([[2, 1, 3],
       [2, 3, 2],
       [1, 3, 1],
       [3, 3, 3]])

In [51]:
arr2.reshape(3,-112398766)

array([[2, 1, 3, 2],
       [3, 2, 1, 3],
       [1, 3, 3, 3]])

In [53]:
arr2.reshape(2,3,2)

array([[[2, 1],
        [3, 2],
        [3, 2]],

       [[1, 3],
        [1, 3],
        [3, 3]]])

In [54]:
arr1 = np.random.randint(1,10,(5,6))

In [55]:
arr1

array([[5, 1, 5, 9, 8, 2],
       [9, 5, 5, 5, 5, 2],
       [8, 7, 1, 1, 8, 4],
       [4, 4, 4, 3, 1, 4],
       [1, 2, 1, 8, 2, 4]])

In [56]:
arr1 > 7

array([[False, False, False,  True,  True, False],
       [ True, False, False, False, False, False],
       [ True, False, False, False,  True, False],
       [False, False, False, False, False, False],
       [False, False, False,  True, False, False]])

In [58]:
arr1[arr1>6]

array([9, 8, 9, 8, 7, 8, 8])

In [59]:
arr1

array([[5, 1, 5, 9, 8, 2],
       [9, 5, 5, 5, 5, 2],
       [8, 7, 1, 1, 8, 4],
       [4, 4, 4, 3, 1, 4],
       [1, 2, 1, 8, 2, 4]])

In [60]:
arr1[0,[0,1]]

array([5, 1])

In [61]:
arr1[2:4 , [2,3]]

array([[1, 1],
       [4, 3]])

In [62]:
arr1[1][1]

5

In [63]:
arr1 = np.random.randint(1,3 , (3,3))

In [72]:
arr2 = np.random.randint(1,3 , (3,3))

In [73]:
arr1

array([[2, 1, 1],
       [2, 2, 1],
       [1, 1, 1]])

In [74]:
arr2

array([[1, 1, 2],
       [1, 2, 1],
       [1, 1, 1]])

In [75]:
arr1 + arr2

array([[3, 2, 3],
       [3, 4, 2],
       [2, 2, 2]])

In [76]:
arr1 - arr2

array([[ 1,  0, -1],
       [ 1,  0,  0],
       [ 0,  0,  0]])

In [78]:
# this is matrix multiplication by indexing 
arr1 * arr2

array([[2, 1, 2],
       [2, 4, 1],
       [1, 1, 1]])

In [79]:
# this is actual matrix multiplication
arr1@arr2

array([[4, 5, 6],
       [5, 7, 7],
       [3, 4, 4]])

In [80]:
arr1/arr2

array([[2. , 1. , 0.5],
       [2. , 1. , 1. ],
       [1. , 1. , 1. ]])

In [81]:
arr1/0

C:\Users\kk\AppData\Local\Temp\ipykernel_7208\1510032488.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [82]:
arr1/1

array([[2., 1., 1.],
       [2., 2., 1.],
       [1., 1., 1.]])

In [83]:
arr1/2

array([[1. , 0.5, 0.5],
       [1. , 1. , 0.5],
       [0.5, 0.5, 0.5]])

In [84]:
# Numpy - BroadCasting

In [85]:
arr = np.zeros((3,4))

In [86]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [87]:
arr + 6

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [92]:
a = np.array([1,2,3,4])

In [93]:
arr + a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [94]:
b = np.array([[3,4,5]])

In [97]:
arr1 = arr + b.T

In [98]:
b.T

array([[3],
       [4],
       [5]])

In [99]:
np.sqrt(arr1)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [100]:
np.log10(arr1)

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [101]:
np.exp(arr1)

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

In [102]:
np.min(arr1)

3.0

In [103]:
np.max(arr1)

5.0