In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5]

In [3]:
arr = np.array(l)

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
type(arr)

numpy.ndarray

In [6]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [7]:
arr1 = np.array([[1,2,3],[2,3,4]])

In [8]:
arr.ndim

1

In [9]:
arr1.ndim

2

In [10]:
arr

array([1, 2, 3, 4, 5])

In [11]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [12]:
mat = np.matrix(l)

In [13]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [14]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5]])

In [15]:
a = arr

In [16]:
a

array([1, 2, 3, 4, 5])

In [17]:
arr[0] = 100

In [18]:
arr

array([100,   2,   3,   4,   5])

In [19]:
a

array([100,   2,   3,   4,   5])

In [20]:
b = np.copy(arr)

In [21]:
b

array([100,   2,   3,   4,   5])

In [22]:
b[0] = 234

In [23]:
b

array([234,   2,   3,   4,   5])

In [24]:
a

array([100,   2,   3,   4,   5])

In [25]:
np.fromfunction(lambda i,j : i==j , (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [26]:
np.fromfunction(lambda i,j : i*j , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [27]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [28]:
iterable = (i*i for i in range(5))

In [29]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [30]:
np.fromstring('23 45 67',sep = " ")

array([23., 45., 67.])

In [31]:
np.fromstring('23,45,67',sep = ",")

array([23., 45., 67.])

In [32]:
arr

array([100,   2,   3,   4,   5])

In [33]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [34]:
arr.ndim

1

In [35]:
arr1.ndim

2

In [36]:
arr.size

5

In [37]:
arr1.size

6

In [38]:
arr.shape

(5,)

In [39]:
arr1.shape

(2, 3)

In [40]:
arr.dtype

dtype('int32')

In [41]:
arr1.dtype

dtype('int32')