In [1]:
import numpy as np

In [2]:
# Numpy - Array Manipulation

In [3]:
arr = np.random.randint(1,10,(4,4))

In [4]:
arr

array([[1, 7, 4, 7],
       [6, 2, 8, 7],
       [5, 3, 4, 9],
       [1, 4, 5, 1]])

In [5]:
arr.reshape(8,2)

array([[1, 7],
       [4, 7],
       [6, 2],
       [8, 7],
       [5, 3],
       [4, 9],
       [1, 4],
       [5, 1]])

In [6]:
arr

array([[1, 7, 4, 7],
       [6, 2, 8, 7],
       [5, 3, 4, 9],
       [1, 4, 5, 1]])

In [8]:
arr.T

array([[1, 6, 5, 1],
       [7, 2, 3, 4],
       [4, 8, 4, 5],
       [7, 7, 9, 1]])

In [9]:
arr.flatten()

array([1, 7, 4, 7, 6, 2, 8, 7, 5, 3, 4, 9, 1, 4, 5, 1])

In [10]:
arr

array([[1, 7, 4, 7],
       [6, 2, 8, 7],
       [5, 3, 4, 9],
       [1, 4, 5, 1]])

In [13]:
np.expand_dims(arr,axis=1)

array([[[1, 7, 4, 7]],

       [[6, 2, 8, 7]],

       [[5, 3, 4, 9]],

       [[1, 4, 5, 1]]])

In [14]:
np.expand_dims(arr,axis=0)

array([[[1, 7, 4, 7],
        [6, 2, 8, 7],
        [5, 3, 4, 9],
        [1, 4, 5, 1]]])

In [17]:
data = np.array([[1],[2],[3]])

In [18]:
np.squeeze(data)

array([1, 2, 3])

In [19]:
np.repeat(data ,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [20]:
np.roll(data ,2)

array([[2],
       [3],
       [1]])

In [21]:
np.roll(data ,3)

array([[1],
       [2],
       [3]])

In [22]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [23]:
data 

array([[1],
       [2],
       [3]])

In [24]:
np.roll(data ,1)

array([[3],
       [1],
       [2]])

In [26]:
# Numpy - Binary Operators

In [27]:
arr1 = np.random.randint(1,10,(3,4))
arr2 = np.random.randint(1,10,(3,4))

In [28]:
arr1 

array([[5, 8, 8, 5],
       [2, 4, 2, 6],
       [7, 2, 6, 3]])

In [29]:
arr2

array([[8, 3, 8, 2],
       [5, 8, 7, 9],
       [4, 3, 5, 9]])

In [30]:
arr1 + arr2

array([[13, 11, 16,  7],
       [ 7, 12,  9, 15],
       [11,  5, 11, 12]])

In [31]:
arr1 - arr2 

array([[-3,  5,  0,  3],
       [-3, -4, -5, -3],
       [ 3, -1,  1, -6]])

In [32]:
arr1 * arr2

array([[40, 24, 64, 10],
       [10, 32, 14, 54],
       [28,  6, 30, 27]])

In [33]:
arr1 / arr2

array([[0.625     , 2.66666667, 1.        , 2.5       ],
       [0.4       , 0.5       , 0.28571429, 0.66666667],
       [1.75      , 0.66666667, 1.2       , 0.33333333]])

In [34]:
arr1 ** arr2

array([[  390625,      512, 16777216,       25],
       [      32,    65536,      128, 10077696],
       [    2401,        8,     7776,    19683]], dtype=int32)

In [35]:
~arr1

array([[-6, -9, -9, -6],
       [-3, -5, -3, -7],
       [-8, -3, -7, -4]], dtype=int32)

In [36]:
arr1 > arr2

array([[False,  True, False,  True],
       [False, False, False, False],
       [ True, False,  True, False]])

In [37]:
# Numpy - String Operation

In [38]:
arr = np.array(["sudh","kumar"])

In [39]:
np.char.upper(arr)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [40]:
np.char.capitalize(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [41]:
np.char.title(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [42]:
arr

array(['sudh', 'kumar'], dtype='<U5')

In [43]:
# Numpy - Mathmatical Function

In [44]:
arr1

array([[5, 8, 8, 5],
       [2, 4, 2, 6],
       [7, 2, 6, 3]])

In [46]:
np.sin(arr1)

array([[-0.95892427,  0.98935825,  0.98935825, -0.95892427],
       [ 0.90929743, -0.7568025 ,  0.90929743, -0.2794155 ],
       [ 0.6569866 ,  0.90929743, -0.2794155 ,  0.14112001]])

In [47]:
np.cos(arr1)

array([[ 0.28366219, -0.14550003, -0.14550003,  0.28366219],
       [-0.41614684, -0.65364362, -0.41614684,  0.96017029],
       [ 0.75390225, -0.41614684,  0.96017029, -0.9899925 ]])

In [48]:
np.tan(arr1)

array([[-3.38051501, -6.79971146, -6.79971146, -3.38051501],
       [-2.18503986,  1.15782128, -2.18503986, -0.29100619],
       [ 0.87144798, -2.18503986, -0.29100619, -0.14254654]])

In [49]:
np.log10(arr1)

array([[0.69897   , 0.90308999, 0.90308999, 0.69897   ],
       [0.30103   , 0.60205999, 0.30103   , 0.77815125],
       [0.84509804, 0.30103   , 0.77815125, 0.47712125]])

In [50]:
np.exp(arr1)

array([[ 148.4131591 , 2980.95798704, 2980.95798704,  148.4131591 ],
       [   7.3890561 ,   54.59815003,    7.3890561 ,  403.42879349],
       [1096.63315843,    7.3890561 ,  403.42879349,   20.08553692]])

In [51]:
np.power(arr1,2)

array([[25, 64, 64, 25],
       [ 4, 16,  4, 36],
       [49,  4, 36,  9]], dtype=int32)

In [52]:
np.mean(arr1)

4.833333333333333

In [53]:
np.median(arr1)

5.0

In [54]:
np.std(arr1)

2.153807997220014

In [55]:
np.var(arr1)

4.638888888888889

In [56]:
np.min(arr1)

2

In [57]:
np.max(arr1)

8

In [58]:
# Numpy - Arithmatics Opeation

In [59]:
arr1 

array([[5, 8, 8, 5],
       [2, 4, 2, 6],
       [7, 2, 6, 3]])

In [60]:
arr2

array([[8, 3, 8, 2],
       [5, 8, 7, 9],
       [4, 3, 5, 9]])

In [61]:
arr1 - arr2

array([[-3,  5,  0,  3],
       [-3, -4, -5, -3],
       [ 3, -1,  1, -6]])

In [62]:
np.subtract(arr1,arr2)

array([[-3,  5,  0,  3],
       [-3, -4, -5, -3],
       [ 3, -1,  1, -6]])

In [63]:
np.multiply(arr1,arr2)

array([[40, 24, 64, 10],
       [10, 32, 14, 54],
       [28,  6, 30, 27]])

In [64]:
np.mod(arr1,arr2)

array([[5, 2, 0, 1],
       [2, 4, 2, 6],
       [3, 2, 1, 3]], dtype=int32)

In [65]:
np.power(arr1,arr2)

array([[  390625,      512, 16777216,       25],
       [      32,    65536,      128, 10077696],
       [    2401,        8,     7776,    19683]], dtype=int32)

In [66]:
np.sqrt(arr1)

array([[2.23606798, 2.82842712, 2.82842712, 2.23606798],
       [1.41421356, 2.        , 1.41421356, 2.44948974],
       [2.64575131, 1.41421356, 2.44948974, 1.73205081]])

In [67]:
# Numpy - Statistical Functions.

In [68]:
arr1 

array([[5, 8, 8, 5],
       [2, 4, 2, 6],
       [7, 2, 6, 3]])

In [69]:
np.mean(arr1)

4.833333333333333

In [70]:
np.median(arr2)

6.0

In [71]:
np.std(arr1)

2.153807997220014

In [72]:
np.var(arr1)

4.638888888888889